language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - add-on
    - extra
    # The BuildTools version used by your project
    - build-tools-26.0.1

    # The SDK version used to compile your project
    - android-26
    - constraint-layout-1.0.2
licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
